sudo: required
dist: trusty
language: 'node_js'
node_js:
  - '12'
  - '10'
node_js: 'node'
install:
  - npm install -g codecov
before_script:
  - node -v
  - npm ci
script:
  - npm run travis
  - npm run codecov
