sudo: required
dist: trusty
language: node_js
node_js:
  - 10
node_js: 'node'
before_script:
  - node -v
  - npm ci
script:
  - npm run travis
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
